name: Convert HTML to Base64 and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'generated_html/*.html'  # Căutați fișiere HTML în repo

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Citim fișierul HTML
      - name: Read HTML File and Encode to Base64
        run: |
          # Citim conținutul fișierului HTML
          html_content=$(cat generated_html/document.html)

          # Convertim HTML în Base64
          base64_content=$(echo -n "$html_content" | base64)

          # Salvăm rezultatul într-un fișier
          echo "$base64_content" > base64_output.txt

      # 3. Copiem fișierul Base64 în folderul public
      - name: Copy Base64 Content to Public Folder
        run: |
          mkdir -p public
          cp base64_output.txt public/

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Folosim branch-ul gh-pages pentru GitHub Pages
          folder: public    # Publicăm din folderul public
          token: ${{ secrets.GITHUB_TOKEN }}  # Token-ul GitHub pentru autentificare
